---
- name: Bastion | Deploy fail2ban jail configuration
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: restart fail2ban
  tags: [bastion_fail2ban]

- name: Bastion | Enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  when: not ansible_check_mode
  tags: [bastion_fail2ban]
