---
- name: Bastion | Allow OpenSSH through UFW
  community.general.ufw:
    rule: allow
    name: OpenSSH
    comment: home-network-v3 bastion ssh
  tags: [bastion_ufw]

- name: Bastion | Set UFW default incoming policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny
  tags: [bastion_ufw]

- name: Bastion | Enable UFW
  community.general.ufw:
    state: enabled
  tags: [bastion_ufw]
