---
- name: Libvirt | Refresh apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: [libvirt]

- name: Libvirt | Install packages
  ansible.builtin.apt:
    name: "{{ hypervisor_libvirt_packages }}"
    state: present
  tags: [libvirt]

- name: Libvirt | Enable and start libvirtd
  ansible.builtin.service:
    name: "{{ hypervisor_libvirt_service }}"
    state: started
    enabled: true
  when: not ansible_check_mode
  tags: [libvirt]
