---
- name: Restart sssd
  ansible.builtin.service:
    name: sssd
    state: restarted
  listen: restart sssd
  when: not ansible_check_mode

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  listen: restart postfix
  when: not ansible_check_mode

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  listen: restart ssh
  when: not ansible_check_mode
