---
- name: Docker engine | Install packages
  ansible.builtin.apt:
    name: "{{ docker_engine_packages }}"
    state: present
  when: docker_engine_enabled | bool
  tags: [docker_engine]

- name: Docker engine | Enable and start docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when:
    - docker_engine_enabled | bool
    - not ansible_check_mode
  tags: [docker_engine]

- name: Docker engine | Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_engine_users }}"
  when:
    - docker_engine_enabled | bool
    - docker_engine_users | length > 0
  tags: [docker_engine]
