---
- name: Install domain join packages
  ansible.builtin.include_tasks: packages.yml
  tags: [domain_packages]

- name: Join AD domain
  ansible.builtin.include_tasks: join.yml
  tags: [domain_join]

- name: Configure SSSD and PAM homedir
  ansible.builtin.include_tasks: configure.yml
  tags: [domain_configure]

- name: Configure sudo for domain groups
  ansible.builtin.include_tasks: sudo.yml
  tags: [domain_sudo]

- name: Configure Postfix relay client
  ansible.builtin.include_tasks: postfix_relayclient.yml
  when:
    - mail_relay_client_enabled | bool
    - "'mail_relay' not in group_names"
  tags: [domain_mail_relay]
