---
hypervisor_libvirt_service: libvirtd
hypervisor_libvirt_image_dir: /var/lib/libvirt/images
hypervisor_libvirt_pool_name: default

hypervisor_libvirt_packages:
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - virtinst
  - bridge-utils
  - python3-libvirt

docker_engine_enabled: true

docker_engine_users:
  - ansible
