---
- name: Restart samba-ad-dc
  ansible.builtin.service:
    name: samba-ad-dc
    state: restarted
  listen: restart samba-ad-dc
  when: not ansible_check_mode

- name: Restart named
  ansible.builtin.service:
    name: named
    state: restarted
  listen: restart named
  when: not ansible_check_mode

- name: Reload apparmor
  ansible.builtin.service:
    name: apparmor
    state: reloaded
  listen: reload apparmor
  when: not ansible_check_mode

- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
  listen: restart chrony
  when: not ansible_check_mode
