---
- name: Pi-hole | Read resolver.resolveIPv6 setting
  ansible.builtin.command:
    cmd: pihole-FTL --config resolver.resolveIPv6
  register: pihole_resolve_ipv6_current
  changed_when: false
  when: pihole_enable_ipv6 | bool

- name: Pi-hole | Enable IPv6 reverse resolution
  ansible.builtin.command:
    cmd: pihole-FTL --config resolver.resolveIPv6 true
  when:
    - pihole_enable_ipv6 | bool
    - pihole_resolve_ipv6_current.stdout | trim != 'true'
  notify: Pi-hole reloaddns
